export const ADD_ALARM_REQUEST = 'ADD_ALARM_REQUEST';
export const ADD_ALARM_SUCCESS = 'ADD_ALARM_SUCCESS';
export const ADD_ALARM_FAILURE = 'ADD_ALARM_FAILURE';

export const PAUSE_ALARM_SUCCESS = 'PAUSE_ALARM_SUCCESS';

export const DELETE_ALARM_REQUEST = 'DELETE_ALARM_REQUEST';
export const DELETE_ALARM_SUCCESS = 'DELETE_ALARM_SUCCESS';
export const DELETE_ALARM_FAILURE = 'DELETE_ALARM_FAILURE';
